name: Build & deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install Flutter
      uses: subosito/flutter-action@v1
      with:
        flutter-version: '2.0.5'

    - name: Update Flutter
      run: flutter upgrade

    - name: Get Dependencies
      run: flutter pub get

    - name: Test Project
      run: flutter test

    - name: Build Release Project
      run: flutter build web --base-href "/EventPlanner/web/"

    - name: Upload production-ready build files
      uses: actions/upload-artifact@v3
      with:
        name: production-files
        path: build/web

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
    - name: Download artifact
      uses: actions/download-artifact@v3
      with:
        name: production-files
        path: build/web

    - name: Deploy to gh-pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.WORKFLOW_TOKEN }}
        publish_dir: build
